name: Publish to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # - uses: actions/checkout@v3
      # - uses: cachix/install-nix-action@v18
      #   with:
      #     github_access_token: ${{ secrets.GITHUB_TOKEN }}
      # - run: nix develop --command trunk build --release --public-url shop

      - uses: actions/checkout@v3
      - name: Cache install Nix packages
        uses: mtoohey31/cache-flake-attrs@v2
        with:
          key: ${{ runner.os }}-nix-${{ hashFiles('./flake.lock', './flake.nix') }}

      - name: Build website
      - run: nix develop --command trunk build --release --public-url shop
        
      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
